README.md
вот если бы заметил секцию сразу - не стал бы задавать глупых вопросов!
=> чаво на глагне!

Compile.bat, Decompile.bat
- добавил вывод русских комментариев, когда в системе основной язык не русский
=> добавил вывод русских комментариев

README.md
Добавил ссылку на обзорную статью о VA Алехина на хабре.
=> Добавил ссылку на обзорную статью VA на хабре

VanessaAutomation/Forms/УправляемаяФорма/Ext/Form.xml
Сделанные изменения:
- Исправил опечатку
=> Исправил опечатку

.bsl-language-server.json
=> #483 Не ругаться на "(,,,)" в VSC

VanessaAutomation/Forms/УправляемаяФорма/Ext/Form.xml
добавил перевод СППР на английский язык
=> добавил перевод СППР на английский язык

VanessaAutomation/Forms/УправляемаяФорма/Ext/Form.xml
реализация  #504
- добавлен перевод
=> добавил перевод кнопки - анг. язык

features/Core/CommandLine/files/TestEN1.json
=> относительные пути

locales/Steps/Templates/ro/Ext/Template.xml
Исправления румынских шагов N2:
- удаление переводов шагов из всех синонимов, кроме русского
- исправление ошибкок
=>  Исправления румынских шагов N2:

locales/Steps/Templates/ro/Ext/Template.xml
Исправление одного румынского шага: добавлен недостающий плейсхолдер
=> Исправление одного румынского шага: добавлен недостающий плейсхолдер

lib/VA_Chrome/library.js
Доработки по интеграции браузера Chrome
- рамка вокруг нескольких элементов формы
- поиск заголовка для элемента формы
=> Доработки по интеграции браузера Chrome

lib/VA_Chrome/library.js
Поиск элементов: Группа, Табличная часть, Навигационная ссылка.
=> Chrome: универсальный поиск элементов формы

README.md
- Добавил ссылку на телеграмм канал
=> Добавил ссылку на телеграмм канал

README.md, VanessaAutomation/Templates/ШаблонЖР/Ext/Template.xml
- Добавил "кнопочки" по статистике скачиваний
=> добавил кнопочки по статистике скачиваний и исправил шаблон с журналом регистрации

.bsl-language-server.json, sonar-project.properties
Изменение формата конфига BSL LS
=> Изменение формата конфига BSL LS

tools/Sikuli/ClickOnPicture.sikuli/ClickOnPicture.py, tools/Sikuli/MoveMouseToPicture.sikuli/MoveMouseToPicture.py
реализация  #854 
- изменил все на табы
=> resolve #854

VanessaAutomation.xml
реализация  #842
- Новый реквизит для контроля: выводить подробный лог или нет.
-
-
=> feat: Новый реквизит для детализации вывода

lib/packages.json
Реализована поддержка редактора VAEditor для Linux с некоторыми ограничениями
=> Обновление редактора VAEditor, версия 1.2.0.14

lib/packages.json
Исправления CSS для поддержки Linux.
=> Обновление редактора VAEditor, версия 1.2.0.15

lib/packages.json
Исправление ошибок VAEditor:
* Точки останова в основном коде
* Генерация события Ctrl+S
=> Обновление редактора VAEditor, версия 1.2.0.16

lib/packages.json
Исправлена ошибка вызова контекстного меню для Linux
=> Обновление редактора VAEditor, версия 1.2.0.17

lib/packages.json
=> Обновление редактора VAEditor, версия 1.2.0.18

lib/packages.json
Удалено автозакрытие символа $$ для параметров
=> Обновление редактора VAEditor, версия 1.2.0.20

lib/packages.json
Компонента содержит новые функции визуализации (только для Windows):
* Поиск фрагмента картинки, поиск фрагмента картинки на экране
* Рисование на экране: прямоугольник, эллипс, стрелка, затенение
```bsl
ВнешняяКомпонента = Новый("AddIn.VanessaExt.WindowsControl");
ВнешняяКомпонента.НастроитьРисование(ЦветКакЧисло(ЦветФигуры), 3000, Толщина, Прозрачность);
ВнешняяКомпонента.НарисоватьПрямоугольник(100, 100, 400, 300);
ВнешняяКомпонента.НарисоватьЭллипс(600, 100, 400, 300);
ВнешняяКомпонента.НарисоватьСтрелку(100, 300, 400, 100);
ПолнаяКартинка = Новый ДвоичныеДанные(ИмяФайлаКартинки);
ФрагментКартинки = Новый ДвоичныеДанные(ИмяФайлаКартинки);
ТекстJSON = ВнешняяКомпонента.НайтиНаЭкране(ПолнаяКартинка, ФрагментКартинки);
ФрагментКартинки = Новый ДвоичныеДанные(ИмяФайлаФрагмента); …
```
=> Обновление компоненты VanessaExt, версия 1.2.3.146

VanessaAutomation/Forms/УправляемаяФорма/Ext/Form.xml
реализация  #1061
- добавил единицу в подсказку на двух языках
- исправил орфографическую ошибку
=> #1061 Добавил единицу измерения в подсказку ТаймаутЗапуска1С

lib/packages.json
Добавлена подсветка и автодополнение операторов исключений
```bsl
Массив = Новый Массив;
Массив.Добавить("Попытка");
Массив.Добавить("Исключение");
Массив.Добавить("КонецПопытки");
ЗаписьJSON = Новый ЗаписьJSON;
ЗаписьJSON.УстановитьСтроку();
ЗаписатьJSON(ЗаписьJSON, Массив);
ТекстJSON = ЗаписьJSON.Закрыть();
VanessaGherkinProvider.setMetatags(ТекстJSON);
```
Добавлена навигация по изменениям текущей вкладки.
```bsl
VanessaTabs.canNavigateDiff()
VanessaTabs.previousDiff()
VanessaTabs.nextDiff()
```
=> Обновление редактора VAEditor, версия 1.2.0.25

lib/packages.json
Исправление ошибки вывода текста в консоль.
=> Обновление компоненты VanessaExt, версия 1.2.3.247

lib/packages.json
Поиск фрагмента изображения на картинке, на экране теперь работает для Linux.
Исправлена запись в консоль Windows: консоль теперь открывается однократно при первом обращении.
Генерация внешнего события при завершении дочернего процесса (для Windows и Linux).
```bsl
&НаКлиенте
Процедура СтартоватьПроцесс(Команда)
КоманднаяСтрока = "ping 127.0.0.1";
СкрытьОкноПроцесса = Истина;
ОписаниеОповещения = Новый ОписаниеОповещения("ПослеСтартаПроцесса", ЭтотОбъект);
ВнешняяКомпонента.НачатьВызовСоздатьПроцесс(ОписаниеОповещения, КоманднаяСтрока, СкрытьОкноПроцесса);
КонецПроцедуры
&НаКлиенте
Процедура ПослеСтартаПроцесса(РезультатВызова, ПараметрыВызова, ДополнительныеПараметры) Экспорт
Если РезультатВызова = 0 Тогда
Сообщить("Ошибка при старте процесса: " + ПараметрыВызова[0]);
Иначе …
```
=> Обновление компоненты VanessaExt, версия 1.2.4.1

lib/packages.json
Исправлена ошибка записи в консоль для Windows 7
=> Обновление компоненты VanessaExt, версия 1.2.4.46

lib/packages.json
Новые функции управления виртуальными рабочими столами (только для Windows):
* ПолучитьКоличествоРабочихСтолов()
* ПолучитьТекущийРабочийСтол()
* СоздатьРабочийСтол()
* УдалитьРабочийСтол(НомерСтола)
* ПереключитьРабочийСтол(НомерСтола)
* ПолучитьРабочийСтолОкна(ИдентификаторОкна)
* ПереместитьОкноНаРабочийСтол(ИдентификаторОкна, НомерСтола)
* ПолучитьГлавноеОкноПроцесса(ИдентификаторПроцесса)
=> Обновление компоненты VanessaExt, версия 1.3.0.65

lib/packages.json
=> Обновление компоненты VanessaExt, версия 1.3.0.82

lib/packages.json
Обновлен парсер Gherkin для раздельного сканирования библиотеки экспортируемых сценариев
=> Обновление компоненты VanessaExt, версия 1.3.0.90

lib/packages.json
Оптимизация парсера Gherkin, исправление ошибок
=> Обновление компоненты VanessaExt, версия 1.3.0.115

lib/packages.json
Обновлен парсер Gherkin: обработка ошибок открытия файлов
=> Обновление компоненты VanessaExt, версия 1.3.0.123

lib/packages.json
Исправления парсера Gherkin для структуры сценария: подстановка шагов, передача параметров, передача таблиц
=> Обновление компоненты VanessaExt, версия 1.3.0.133

lib/packages.json
Развитие функционала парсера Gherkin
=> Обновление компоненты VanessaExt, версия 1.3.0.137

lib/packages.json
Добавлено свойство: VanessaTabs.renderWhitespace.
Возможные значения: 'none', 'boundary', 'selection', 'all'.
```js
VanessaTabs.renderWhitespace = "all";
```
=> Обновление редактора VAEditor, версия 1.2.0.29

lib/packages.json
Исправлена обработка многословных ключевых слов
=> Обновление редактора VAEditor, версия 1.2.0.30

VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
Issue:
#1166
Cделанные изменения:
- Fixed step description;
- Fixed and changed refill constant step name and description;
=> issue#1166 Update Module.bsl 

lib/packages.json
Исправлена ошибка обработки символа №
=> Обновление компоненты VanessaExt, версия 1.3.0.139

lib/packages.json
Подсветка и синтаксический контроль условных операторов
```bsl
УсловныеОператоры = Новый Соответствие;
МассивСлов = Новый Массив;
МассивСлов.Добавить("then");
УсловныеОператоры.Вставить("if", МассивСлов);
МассивСлов = Новый Массив;
МассивСлов.Добавить("Тогда");
УсловныеОператоры.Вставить("Если", МассивСлов);
ЗаписьJSON = Новый ЗаписьJSON;
ЗаписьJSON.УстановитьСтроку();
ЗаписатьJSON(ЗаписьJSON, УсловныеОператоры);
УсловныеОператоры = ЗаписьJSON.Закрыть();
GherkinProvider.setKeypairs(УсловныеОператоры);
```
=> Обновление редактора VAEditor, версия 1.2.0.32

lib/packages.json
Парсер Gherkin: исправлена обработка пустых ячеек таблицы
=> Обновление компоненты VanessaExt, версия 1.3.0.145

lib/packages.json
Парсер Gherkin: подстановка параметров через квадратные скобки
=> Обновление компоненты VanessaExt, версия 1.3.1.0

lib/packages.json
Парсер Gherkin: исправлена подстановка параметров
=> Обновление компоненты VanessaExt, версия 1.3.1.1

lib/packages.json
Исправлена ошибка разбора реквизита, потеря буквы "Р"
Для многострочных параметров сделано форматирование и отключена проверка синтаксиса
=> Обновление компоненты VanessaExt и редактора VAEditor

lib/packages.json
Исправление ошибки проверки синтаксиса
=> Обновление редактора VAEditor, версия 1.2.0.37

lib/packages.json
Новые функции автоматизации UI Automation:
Свойства:
* АктивныйЭлемент
Методы:
* ПолучитьЭлементы
* НайтиЭлементы
* ВызватьЭлемент
Новые функции обработки изображений:
* МасштабироватьИзображение
* ОбрезатьИзображение
=> Обновление компоненты VanessaExt, версия 1.3.2.57

lib/packages.json
Развитие функций автоматизации UI Automation
Исправлен вывод в консоль версии для CentOS
=> Обновление компоненты VanessaExt, версия 1.3.2.75

lib/packages.json
Исправлена ошибка получения масштаба для старых версий Windows
=> Обновление компоненты VanessaExt, версия 1.3.3.25

lib/packages.json
Добавлена функция получения родителя 
```bsl
ВК.ПолучитьРодителяЭлемента(Ид);
```
=> Обновление компоненты VanessaExt, версия 1.3.3.29

lib/packages.json
Исправлен поиск элементов формы
=> Обновление компоненты VanessaExt, версия 1.3.3.31

lib/packages.json
Ускоряем поиск главного окна для UI Automation
=> Обновление компоненты VanessaExt, версия 1.3.3.32

lib/packages.json
=> Обновление компоненты VanessaExt, версия 1.3.3.40

VanessaAutomation/Ext/Help/ru.html
- в справке (ru) дополнил описание работы с глобальными переменными
=> Дополнил описание работы с глобальными переменными

lib/packages.json
Добавлено свойство UI Automation: фокус ввода клавиатуры
=> Обновление компоненты VanessaExt, версия 1.3.3.61

lib/packages.json
Обновление редактора VAEditor:
* Исправлено отображение ссылок вида e1cib
* Сложные составные переменные из таблиц
* Добавлена иконка для озвучивания шага
=> Обновление редактора VAEditor, версия 1.3.0.2

lib/packages.json
Развитие функционала секции "Переменные":
* Исправлено определение ссылок e1cib
* Гиперссылки для простых назначаемых переменных
* Поддержка многострочных переменных
* Форматирование переменных
=> Обновление редактора VAEditor, версия 1.3.0.3

lib/packages.json
Форматирование кода внутри фигурных скобок
=> Обновление редактора VAEditor, версия 1.3.0.4

lib/packages.json
Форматирование многострочных параметров и переменных #1279
=> Обновление редактора VAEditor, версия 1.3.0.5

VanessaAutomation/Forms/ПарсерGherkin/Ext/Form/Module.bsl, lib/packages.json
Обновление компоненты VanessaExt, версия 1.3.4.0
* Добавлено ключевое слово: Переменные
* Разбор секции Переменные
=> Обновление компоненты VanessaExt, версия 1.3.4.0

lib/packages.json
Добавлено поле, содержащее полный путь импортируемого файла Gherkin
Добавлен метод, позволяющий получить кэшируемые файлы с переменными
=> Обновление компоненты VanessaExt, версия 1.3.4.5

lib/packages.json
Добавлен метод подключения импортированных файлов
```bsl
ТекстJSON = ВнешняяКомпонентаПарсерGherkin.Переменные;
VanessaGherkinProvider.setImports(ТекстJSON);
```
Или асинхронный вызов:
```bsl
ОписаниеОповещения = Новый ОписаниеОповещения("ПолученыПеременные", ЭтотОбъект);
ВнешняяКомпонентаПарсерGherkin.НачатьПолучениеПеременные(ОписаниеОповещения);
&НаКлиенте
Процедура ПолученыПеременные(Результат, ДополнительныеПараметры) Экспорт
VanessaGherkinProvider.setImports(Результат);
КонецПроцедуры
```
=> Обновление редактора VAEditor, версия 1.3.0.6

VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form.xml, VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
#1237
#1242 
реализация  #
Добавлены изменения от CryptCat (https://github.com/CryptKat): 
- Работает "Выбрать зависимые элементы" для русского варианта.
- Поддержка реквизитов с русскими именами, совпадающиими с системными реквизитами
- Экранирование переносов строк и других спец-символов
- Возможность отбора по ссылкам и их зависимостям
- Добавление объекта в список отбора по навигационной ссылке
- Заполнение ссылочных реквизитов объекта "вводом по строке"
- Новый шаг "И я проверяю или создаю для регистра сведений записи используя наборы записей:"
Исправлены незначительные ошибки.
=> #1237 #1242

VanessaAutomation/Forms/УправляемаяФорма/Ext/Form.xml
=> docs: Дополнил инструкцию про СберТТС

lib/packages.json
Добавлен метод компоненты для отображения подсказки
```bsl
ВремСтруктура = Новый Структура;
ВремСтруктура.Вставить("color", ЦветКакЧисло(ЦветКонтура));
ВремСтруктура.Вставить("background", ЦветКакЧисло(ЦветФона));
ВремСтруктура.Вставить("fontColor", ЦветКакЧисло(ЦветТекста));
ВремСтруктура.Вставить("fontName", ШрифтНадписи.Имя);
ВремСтруктура.Вставить("fontSize", ШрифтНадписи.Размер);
ВремСтруктура.Вставить("radius", РадиусЗакругления);
ВремСтруктура.Вставить("thickness", ТолщинаКонтура);
ВремСтруктура.Вставить("duration", Длительность);
ЗаписьJSON = Новый ЗаписьJSON;
ЗаписьJSON.УстановитьСтроку();
ЗаписатьJSON(ЗаписьJSON, Данные);
НастройкиРисования = ЗаписьJSON.Закрыть();
ВнешняяКомпонента.НачатьВызовПоказатьПодсказку(
Новый ОписаниеОповещения, НастройкиРисования, 
ПозицияСлева, …
```
=> Обновление компоненты VanessaExt, версия 1.3.5.2

VanessaAutomation/Forms/УправляемаяФорма/Ext/Form.xml, VanessaAutomation/Forms/УправляемаяФорма/Ext/Form/Module.bsl, lib/packages.json
Отображение статуса inline debug
```bsl
VanessaEditor.setRuntimeProgress(СтатусШага, НомерСтроки, ИдВиджета, ИнлайнТекст);
```
На форму добавлена информация о версии редактора
Исправлена ошибка выделения групп
=> Обновление редактора VAEditor, версия 1.3.2.2

features/Core/ScreenShot/Окно прерывания процесса.feature, lib/packages.json
Внесена поправка для координат видеоэффекта подсказки
=> Обновление компоненты VanessaExt, версия 1.3.5.45

lib/packages.json
Темная тема для окна приветствия и просмотра Markdown.
Исправлена ошибка потери пробела при подстановке шагов.
=> Темная тема для окна просмотра и подбор шагов

lib/packages.json
Инициализация пиктограмм для начальной страницы
=> Обновление редактора VAEditor, версия 1.3.3.14

lib/packages.json
Инициализация пиктограмм для начальной страницы
=> Обновление редактора VAEditor, версия 1.3.3.15

VanessaAutomation/Forms/НастройкаРедактора/Ext/Form/Module.bsl, lib/packages.json
Обновление версии Monaco Editor 0.30.1
Определение координат позиции текста
```js
Координаты1 = VanessaTabs.getCoordinates(lineNumber, column);
Координаты2 = VanessaTabs.getRectangle(startLineNumber, startColumn, endLineNumber, endColumn);
```
=> Обновление редактора VAEditor, версия 1.3.4.1

lib/packages.json
Исправлен метод получения координат и стиль гиперссылок
=> Обновление редактора VAEditor, версия 1.3.4.11

lib/packages.json
=> Обновление компоненты VanessaExt, версия 1.3.6.9

lib/packages.json
Исправлена свертка групп со звездочкой
=> Обновление редактора VAEditor, версия 1.3.4.23

lib/packages.json
Определен тип подключения компоненты: GetAttachType()
Визуализация нажатия кнопки эффекта затенения
=> Обновление компоненты VanessaExt, версия 1.3.7.1

lib/packages.json
Событие при закрытии эффекта затенения по таймауту
=> Обновление компоненты VanessaExt, версия 1.3.7.2

lib/packages.json
Исправления для эффекта затенения
=> Обновление компоненты VanessaExt, версия 1.3.7.4

lib/packages.json
Переключение вкладок нажатием CTRL+1, CTRL+2 и так далее
=> Обновление редактора VAEditor, версия 1.3.4.24

lib/packages.json
Эффект затенения для нескольких мониторов
Круглые кнопки для эффекта затенения
=> Обновление компоненты VanessaExt, версия 1.3.7.7

lib/packages.json
Исправление ошибки парсера Gherkin при записи в JSON чисел с плавающей точкой
=> Обновление компоненты VanessaExt, версия 1.3.7.9

lib/packages.json
Подстановка параметров типа Число и Дата в парсере Gherkin
=> Обновление компоненты VanessaExt, версия 1.3.7.23

docs/index.md
=> Добавил ссылку на видео

lib/VAExtension/Configuration.xml
=> Заполнил основную роль в VAExtension

lib/packages.json
Добавлены новые свойства типа Булево:
* МониторингСобытийМыши
* МониторингАктивногоЭлемента
=> Обновление компоненты VanessaExt, версия 1.3.8.4

lib/packages.json
Удален мониторинг событий клавиатуры
=> Обновление редактора VAEditor, версия 1.3.5.26

lib/packages.json
Удалена подписка на события изменения содержимого
=> Обновление редактора VAEditor, версия 1.3.5.27

lib/packages.json
Удален обработчик POSITION_DID_CHANGE
=> Обновление редактора VAEditor, версия 1.3.5.28

lib/packages.json
Исправлена позиция кнопок эффекта затенения
=> Обновление компоненты VanessaExt, версия 1.3.8.5

lib/packages.json
Проверка наличия двоеточия для ключевых слов верхнего уровня в парсере Gherkin
=> Обновление компоненты VanessaExt, версия 1.3.8.14

lib/packages.json
Обновление компоненты VanessaExt, версия 1.3.8.23
=> Обработка ошибки получения снимка окна для Linux

lib/packages.json
Дополнительные свойства окон Linux: тип и статус окна.
=> Обновление компоненты VanessaExt, версия 1.3.8.33

lib/packages.json
Наполнение шагов в примерах структуры сценария
=> Обновление компоненты VanessaExt, версия 1.3.8.38

lib/packages.json
=> Обновление компоненты VanessaExt, версия 1.3.8.46

lib/packages.json
Новый параметр для эффекта затенения: ignoreClick
=> Обновление компоненты VanessaExt, версия 1.3.8.48

lib/packages.json
Поиск файлов и папок: параметр ИскатьВПодкаталогах
Игнорируем миллисекунды даты модификации файла
=> Обновление компоненты VanessaExt, версия 1.3.9.3

docs/index.md
=> Добавлена ссылка на видео с митапа Инфостарта

lib/packages.json
Исправлена обработка парсером пустой группы со звездочкой
=> Обновление компоненты VanessaExt, версия 1.3.9.7

lib/packages.json
Исправление ошибок:
* https://github.com/lintest/VanessaExt/issues/67
* https://github.com/lintest/VanessaExt/issues/66
=> Обновление компоненты VanessaExt, версия 1.3.9.9

lib/packages.json
Генерация события PRESS_ESCAPE при нажатии клавиши Esc 
* https://github.com/Pr-Mex/VAEditor/issues/143
=> Обновление редактора VAEditor, версия 1.3.5.29

lib/packages.json
Заполнение тегов шагов подсценария https://github.com/lintest/VanessaExt/issues/69
=> Обновление компоненты VanessaExt, версия 1.3.9.10

lib/packages.json
Добавлена поддержка языков CSS, JSON, HTML
=> Обновление редактора VAEditor, версия 1.3.6.1

lib/packages.json
Прерывание длительной операции
```bsl
ВнешняяКомпонента.НачатьВызовПоказатьОкноПрерывания(
Новый ОписаниеОповещения, ТекстJSON, Текст, "Стоп", "C:\TEMP\STOP.TXT");
```
=> Обновление компоненты VanessaExt, версия 1.3.9.14

VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
=> fix: Удалена избыточная проверка измерения на свойство Ведущий #1849

lib/packages.json
Найденные файлы сценариев сортируются по алфавиту
=> Обновление компоненты VanessaExt, версия 1.3.9.21

VanessaAutomation.xml, VanessaAutomation/Forms/ВводСтрокиНавигационныхСсылок.xml, VanessaAutomation/Forms/ВводСтрокиНавигационныхСсылок/Ext/Form.xml, VanessaAutomation/Forms/ВводСтрокиНавигационныхСсылок/Ext/Form/Module.bsl, VanessaAutomation/Forms/ПодготовкаИЗагрузкаДанных/Ext/Form/Module.bsl
Улучшение работы "Подготовки и загрузки данных" "Добавить по ссылке"
реализация  #1958 
Заменена платформенная форма ввода строки на форму ВводСтрокиНавигационныхСсылок
в форме ВводСтрокиНавигационныхСсылок есть кнопка которая очищает не корректные подстроки(которые не являются навигационной ссылкой)
=> #1958 Улучшение Подготовки и загрузки данных

lib/packages.json
Прерывание эмуляции ввода текста
=> Обновление компоненты VanessaExt, версия 1.3.9.29

VanessaAutomation/Templates/CSS_3D_Сarousel/Ext/Template.txt
добавил возможность прокручивать стрелками клавиатуры карусель
реализация  #2024
=> Добавил возможность прокрутки стрелками клавиатуры Карусель 3Д

docs/index.md
=> Актуализировал список

lib/packages.json
=> Обновление компоненты VanessaExt, версия 1.3.9.69

docs/index.md
=> в документацию добавлена ссылка на статью по настройке gitlab и vanessa automation

lib/packages.json
При получении свойств процесса Windows также получаем значение занятой памяти https://github.com/lintest/VanessaExt/issues/81
Обновление компоненты VanessaExt, версия 1.3.9.77
=> При получении свойств процесса Windows также получаем значение занятой памяти 

lib/packages.json
Исправлен метод НайтиКлиентТестирования() для версии платформы 8.5
=> Обновление компоненты VanessaExt, версия 1.3.9.90

lib/packages.json
Получение снимка окна для версии платформы 8.5
=> Обновление компоненты VanessaExt, версия 1.3.9.91
